var questions = [
    {
        title: 'What tag do we use to link your CSS/JS script in HTML',
        choices: ['script', 'link', 'a href', 'style'],
        answer: 'script',
    },
    {
        title: 'In CSS how do we target a "id"',
        choices: ['.', 'id', '#', 'the targeted tag'],
        answer: '#'
    },
    {
        title: 'In JS how do we test if our function is working?',
        choices: ['aleart', 'restart the entire website', 'asking your friend', 'console.log'],
        answer: 'console.log'
    },
    {
        title:
          'String values must be enclosed within ____ when being assigned to variables.',
        choices: ['commas', 'curly brackets', 'quotes', 'parentheses'],
        answer: 'quotes',
      },
];